travis:
  secure:
    BINSTAR_TOKEN: flxUrh9z4agEoDZKuL//NjJuSySuxxKwEYo2fPAexxSde4erGRdc1kAC3uvTZRc0fQciWMNJlzkcGCwFEFS+xRT4wGJ9rOaFbjCnr/CyEZwrCzdxpLjSjAAfPiOKKBeE+jhpzD1jkGvKU/E8ex/vWPtf0NM+X8J4rx6nI7R4m1+yFqkZUX2wLMG4u3O54cfG5PQhgiOaj8UR3zo8Gryhh1YpcK4lEy4APlTurcoor12P7BsrPMYO7PHbXgXpgK24bqLtXN0ZNWMd3ysVkX2h58xEDqiwujZ4S4JczCtbr7KWKODzWTWC39Sztgylv0WAGbTzRh4gEJEeniNdJQ+Fl3bL7zxjLHJHEcR6NVtxECe4u3zO5bSwVdKuOFpKESiS71pAmUMh3FBZFUWcmIS3Gwx8UYvC8LCZAkIehaEdja8g+C9odvB3BXIXc4naFu0i9NrgJC4LaYIAoKz9jLw/ueRmLDxkdIZf9vFkFi/s2jYyHoUerbKceM6aoaNr2IhxWmQRqf1A+ddGZ63xBQR7jcbUmiQJrgQSFSZJLEXK0QYtCEIgRos0+Aai76C6W+dQQ9CU8DievoQ/MWIDVH8CFkGS5w0380g36pLrEini5lOhvHDNi9lZfGuQ/waQyEt9z/ip1UGqlOvYhAKDpe4z4MeY33ycyXS/H45NaR7B4wg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
